version: "3"

services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/var/www/project/
    depends_on:
      - db
    links:
      - db
    user: ${CURRENT_UID}
    networks:
      - common_network
    environment:
      DATABASE_URL: mysql://noel:flantier@db:3306/follow
      DATABASE_TEST_URL: mysql://noel:flantier@db_test:3306/follow_test
      WAIT_HOSTS: db:3306

  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - api
    links:
      - api
    volumes:
      - ./api:/var/www/project/
    ports:
      - 8001:80
    networks:
      - common_network

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: follow
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3311:3306
    networks:
      - common_network

  # disable it if you don't use automatic tests (and if you like to kill kitten)
  db_test:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: follow_test
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3313:3306
    networks:
      - common_network

networks:
  common_network:
    external:
      name: common

