version: "3"

services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/var/www/project/
    user: ${CURRENT_UID}
    networks:
      - symfony
    environment:
      DATABASE_URL: mysql://noel:flantier@db:3306/follow
      DATABASE_TEST_URL: mysql://noel:flantier@db_test:3306/follow_test
      WAIT_HOSTS: db:3306

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./api:/var/www/project/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8001:80
    networks:
      - symfony

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: follow
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3311:3306
    networks:
      - symfony

  # disable it if you don't use automatic tests (and if you like to kill kitten)
  db_test:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: follow_test
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3313:3306
    networks:
      - symfony

networks:
  symfony:

