version: "3"

services:
  api:
    build:
      context: ./api
    environment:
      - DATABASE_URL=mysql://noel:flantier@db:3306/follow
    volumes:
      - ./api:/var/www/project/
    networks:
      - common_network

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./api:/var/www/project/
    ports:
      - 8001:80
    networks:
      - common_network

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3311:3306
    networks:
      - common_network

networks:
  common_network:
    external:
      name: common

