version: "3"

services:
  fpm:
    build:
      context: ./docker/php
    environment:
      - DATABASE_URL=mysql://noel:flantier@db:3306/follow
    volumes:
      - ./api:/var/www/project/
    networks:
      - symfony

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./api:/var/www/project/
    ports:
      - 8001:80
    networks:
      - symfony

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    volumes:
#      - symfony_db:/var/lib/mysql:cached
    ports:
      - 3311:3306
    networks:
      - symfony

networks:
  symfony:
