api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    # Enable the Swagger documentation and export.
    enable_swagger: true

    # Enable Swagger ui.
    enable_swagger_ui: true

    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
