services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']


    # Listeners
    App\EntityHook\EntitySubscriber:
        autoconfigure: false
        tags:
            - { name: doctrine.event_subscriber }
